---
name: "cpp-release"

on:
  push:
    tags:
      - "v*"

jobs:
  cpp-release:
    name: "C++ Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'grpc/grpc'
          ref: 'grpc-1.46.3'
          submodules: 'true'
          path: '..'
      - name: 

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn package -Dmaven.test.skip=true
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/target/*.tar.gz
            dist/target/*.zip